name: 'Deployment'
description: 'Deployment'
inputs:
  os:
    description: 'os'
    required: true
    default: Linux

runs:
  using: composite
  steps:
      - if: ${{ inputs.os == 'Linux' }}
        run: |
          curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ inputs.github-token }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{inputs.org}}/${{inputs.repo}}/actions/artifacts/${{inputs.artifactId}}/zip -o ${{inputs.path}}
            pwd
        shell: bash