name: 'Deployment'

on:
  workflow_call:
  
    inputs:
      os:
        description: 'os'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-linux
    
    steps:
      - name: Run
        run: |
            echo ${{inputs.os}}
        shell: bash
